import type {
  AppConfig,
  DiagnosticTarget,
  DnsProfile,
} from "./types.js";

export const DEFAULT_DIAGNOSTIC_TARGETS: DiagnosticTarget[] = [
  { id: "cf", name: "Cloudflare", host: "1.1.1.1" },
  { id: "epic", name: "Epic Games", host: "www.epicgames.com" },
  { id: "gemini", name: "Gemini", host: "www.google.com" },
  { id: "steam", name: "Steam", host: "store.steampowered.com" },
  { id: "yt", name: "YouTube", host: "www.youtube.com" },
  { id: "gpt", name: "ChatGPT", host: "chat.openai.com" },
  { id: "git", name: "GitHub", host: "github.com" },
];

export const DEFAULT_PRESETS: DnsProfile[] = [
  {
    id: "preset_cloudflare",
    name: "Cloudflare",
    primary_ipv4: "1.1.1.1",
    secondary_ipv4: "1.0.0.1",
    primary_ipv6: "2606:4700:4700::1111",
    secondary_ipv6: "2606:4700:4700::1001",
    doh_url: "https://cloudflare-dns.com/dns-query",
    dot_host: "one.one.one.one",
    favorite: true,
    preset: true,
  },
  {
    id: "preset_google",
    name: "Google",
    primary_ipv4: "8.8.8.8",
    secondary_ipv4: "8.8.4.4",
    primary_ipv6: "2001:4860:4860::8888",
    secondary_ipv6: "2001:4860:4860::8844",
    doh_url: "https://dns.google/dns-query",
    dot_host: "dns.google",
    favorite: false,
    preset: true,
  },
  {
    id: "preset_quad9",
    name: "Quad9",
    primary_ipv4: "9.9.9.9",
    secondary_ipv4: "149.112.112.112",
    primary_ipv6: "2620:fe::fe",
    secondary_ipv6: "2620:fe::9",
    doh_url: "https://dns.quad9.net/dns-query",
    dot_host: "dns.quad9.net",
    favorite: false,
    preset: true,
  },
  {
    id: "preset_opendns",
    name: "OpenDNS",
    primary_ipv4: "208.67.222.222",
    secondary_ipv4: "208.67.220.220",
    primary_ipv6: "2620:119:35::35",
    secondary_ipv6: "2620:119:53::53",
    doh_url: null,
    dot_host: null,
    favorite: false,
    preset: true,
  },
  {
    id: "preset_adguard",
    name: "AdGuard",
    primary_ipv4: "94.140.14.14",
    secondary_ipv4: "94.140.15.15",
    primary_ipv6: "2a10:50c0::ad1:ff",
    secondary_ipv6: "2a10:50c0::ad2:ff",
    doh_url: "https://dns.adguard-dns.com/dns-query",
    dot_host: "dns.adguard-dns.com",
    favorite: false,
    preset: true,
  },
  {
    id: "preset_mullvad",
    name: "Mullvad",
    primary_ipv4: "194.242.2.2",
    secondary_ipv4: "194.242.2.3",
    primary_ipv6: "2a07:e3400::2",
    secondary_ipv6: "2a07:e3400::3",
    doh_url: "https://doh.mullvad.net/dns-query",
    dot_host: "doh.mullvad.net",
    favorite: false,
    preset: true,
  },
  {
    id: "preset_shecan",
    name: "Shecan",
    primary_ipv4: "178.22.122.100",
    secondary_ipv4: "185.51.200.2",
    primary_ipv6: null,
    secondary_ipv6: null,
    doh_url: null,
    dot_host: null,
    favorite: false,
    preset: true,
  },
  {
    id: "preset_electro",
    name: "Electro",
    primary_ipv4: "78.157.42.100",
    secondary_ipv4: "78.157.42.101",
    primary_ipv6: null,
    secondary_ipv6: null,
    doh_url: null,
    dot_host: null,
    favorite: false,
    preset: true,
  },
  {
    id: "preset_403online",
    name: "403.online",
    primary_ipv4: "10.202.10.10",
    secondary_ipv4: "10.202.10.11",
    primary_ipv6: null,
    secondary_ipv6: null,
    doh_url: null,
    dot_host: null,
    favorite: false,
    preset: true,
  },
  {
    id: "preset_radargame",
    name: "Radar Game",
    primary_ipv4: "10.202.10.10",
    secondary_ipv4: "10.202.11.11",
    primary_ipv6: null,
    secondary_ipv6: null,
    doh_url: null,
    dot_host: null,
    favorite: false,
    preset: true,
  },
];

export const DEFAULT_CONFIG: AppConfig = {
  active_profile_id: null,
  is_connected: false,
  profiles: DEFAULT_PRESETS,
  history: [],
  rules: [],
  auto_switch_rules: [],
  auto_switch_enabled: false,
  settings: {
    theme: "dark",
    doh_enabled: false,
    dns_encryption_type: "doh",
    ipv6_enabled: false,
    minimize_to_tray: true,
    start_on_boot: false,
    active_adapter_id: null,
    diagnostic_targets: DEFAULT_DIAGNOSTIC_TARGETS,
    auto_ping_enabled: true,
    auto_update: false,
  },
  schema_version: 3,
};

export const SCHEMA_VERSION = 3;